In [111]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [112]:
data=pd.DataFrame({"text":["people watch cricket","cricket watch cricket","people give comment","cricket give comment"],"output":[1,1,0,0]})
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [113]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


data = pd.DataFrame({
    "text": ["people watch cricket", "cricket watch cricket", "people give comment", "cricket give comment"],
    "output": [1, 1, 0, 0]
})


tokenized_sentences = [sentence.split() for sentence in data['text']]
print(f'Sentences tokenized into words:\n{tokenized_sentences}')


unique_words = sorted(list(set(" ".join(data['text']).split())))
print(f'Unique words (vocabulary):\n{unique_words}')

# Step 3: Initialize OneHotEncoder and Fit with Vocabulary
one_hot_encoder = OneHotEncoder(sparse_output=False)  # Ensure dense output
one_hot_encoder.fit([[word] for word in unique_words])  # Fit encoder on unique words

# Step 4: Encode Each Sentence
encoded_sentences = []
for sentence in tokenized_sentences:
    # Transform each word in the sentence into one-hot encoding
    encoded_sentence = one_hot_encoder.transform([[word] for word in sentence])
    encoded_sentences.append(encoded_sentence)


print("\nOne-Hot Encoded Sentences:")
for i, encoded_sentence in enumerate(encoded_sentences):
    print(f"Sentence {i + 1}:")
    print(encoded_sentence)



Sentences tokenized into words:
[['people', 'watch', 'cricket'], ['cricket', 'watch', 'cricket'], ['people', 'give', 'comment'], ['cricket', 'give', 'comment']]
Unique words (vocabulary):
['comment', 'cricket', 'give', 'people', 'watch']

One-Hot Encoded Sentences:
Sentence 1:
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
Sentence 2:
[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
Sentence 3:
[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
Sentence 4:
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [114]:
import pandas as pd

data = pd.DataFrame({
    "text": ["people watch cricket", "cricket watch cricket", "people give comment", "cricket give comment"],
    "output": [1, 1, 0, 0]
})

# Initialize an empty list to store the tokenized sentences
tokenized_sentences = []

# Loop through each sentence in the 'text' column
for sentence in data['text']:
    # Split the sentence into words and append it to the tokenized_sentences list
    tokenized_sentence = sentence.split()
    tokenized_sentences.append(tokenized_sentence)

# Print the result
print(tokenized_sentences)

[['people', 'watch', 'cricket'], ['cricket', 'watch', 'cricket'], ['people', 'give', 'comment'], ['cricket', 'give', 'comment']]


In [115]:
### Now lets go for BOW 


BOW = CountVectorizer()
sentance_encoder = BOW.fit_transform(data['text'])

print(sentance_encoder)

BOW.vocabulary_

print(documents_matrix[0].toarray())
print(documents_matrix[1].toarray())

pd.DataFrame(sentance_encoder.toarray(),columns=BOW.get_feature_names_out())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 11 stored elements and shape (4, 5)>
  Coords	Values
  (0, 3)	1
  (0, 4)	1
  (0, 1)	1
  (1, 4)	1
  (1, 1)	2
  (2, 3)	1
  (2, 2)	1
  (2, 0)	1
  (3, 1)	1
  (3, 2)	1
  (3, 0)	1
[[0 1 0 1 1]]
[[0 2 0 0 1]]


comment  cricket  give  people  watch
0        0        1     0       1      1
1        0        2     0       0      1
2        1        0     1       1      0
3        1        1     1       0      0

In [116]:
#### Implementation for N-Gram

BOW = CountVectorizer(ngram_range=(1,2))
sentance_encoder = BOW.fit_transform(data['text'])

print(sentance_encoder)

BOW.vocabulary_

pd.DataFrame(sentance_encoder.toarray(),columns=BOW.get_feature_names_out())

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 19 stored elements and shape (4, 11)>
  Coords	Values
  (0, 6)	1
  (0, 9)	1
  (0, 1)	1
  (0, 8)	1
  (0, 10)	1
  (1, 9)	1
  (1, 1)	2
  (1, 10)	1
  (1, 3)	1
  (2, 6)	1
  (2, 4)	1
  (2, 0)	1
  (2, 7)	1
  (2, 5)	1
  (3, 1)	1
  (3, 4)	1
  (3, 0)	1
  (3, 5)	1
  (3, 2)	1


comment  cricket  cricket give  cricket watch  give  give comment  people  \
0        0        1             0              0     0             0       1   
1        0        2             0              1     0             0       0   
2        1        0             0              0     1             1       1   
3        1        1             1              0     1             1       0   

   people give  people watch  watch  watch cricket  
0            0             1      1              1  
1            0             0      1              1  
2            1             0      0              0  
3            0             0      0              0

### Lets lets do some practise Problems 


In [117]:
import numpy as np
# Problem 1: One-Hot Encode Sentences
# Task: Create one-hot encoded vectors for the following sentences:

Sentance = ["I love programming", "programming is fun", "love and fun"]

tokenized_sentance = [words.split() for words in Sentance]
print("splitted the words in the sentance:\n",tokenized_sentance)

all_words = []
for sentance in tokenized_sentance:
    for words in sentance:
        all_words.append(words)

print('All the words in the Sentance:\n',all_words)

unique_words= sorted(list(set(all_words)))

print('Unique words in all_words:\n',unique_words)


Onehot = OneHotEncoder(sparse_output=False)

# encoded for each word 
Onehot_encoder=Onehot.fit([[words] for words in unique_words])
print(Onehot_encoder)


encoded_sentances = []
for sentance in tokenized_sentance:
    encoded_sentence = Onehot_encoder.transform([[words] for words in sentance])
    encoded_sentances.append(encoded_sentence)


for i, sentance in enumerate(encoded_sentences):
    print(f'Sentance {i+1}:\n')
    print(sentance)






splitted the words in the sentance:
 [['I', 'love', 'programming'], ['programming', 'is', 'fun'], ['love', 'and', 'fun']]
All the words in the Sentance:
 ['I', 'love', 'programming', 'programming', 'is', 'fun', 'love', 'and', 'fun']
Unique words in all_words:
 ['I', 'and', 'fun', 'is', 'love', 'programming']
OneHotEncoder(sparse_output=False)
Sentance 1:

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
Sentance 2:

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]]
Sentance 3:

[[0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]
Sentance 4:

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [118]:
data

text  output
0   people watch cricket       1
1  cricket watch cricket       1
2    people give comment       0
3   cricket give comment       0

In [119]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [120]:
tfidf = TfidfVectorizer()

In [122]:
tfidf.fit_transform(data['text']).toarray()

array([[0.        , 0.49681612, 0.        , 0.61366674, 0.61366674],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357],
       [0.57735027, 0.        , 0.57735027, 0.57735027, 0.        ],
       [0.61366674, 0.49681612, 0.61366674, 0.        , 0.        ]])

In [123]:
tfidf.get_feature_names_out()

array(['comment', 'cricket', 'give', 'people', 'watch'], dtype=object)

In [124]:
tfidf.idf_

array([1.51082562, 1.22314355, 1.51082562, 1.51082562, 1.51082562])

In [125]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api


ModuleNotFoundError: No module named 'gensim'

In [126]:
pip install gensim

  Using cached smart_open-7.0.5-py3-none-any.whl.metadata (24 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.0/24.0 MB 18.7 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 52.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 30.3/30.3 MB 23.4 MB/s eta 0:00:0000:0100:01
Using cached smart_open-7.0.5-py3-none-any.whl (61 kB)
  Attempting uninstall: numpy
    Found existing installation: numpy 2.1.3
    Uninstalling numpy-2.1.3:
      Successfully uninstalled numpy-2.1.3
  Attempting uninstall: scipy
    Found existing installation: scipy 1.14.1
    Uninstalling scipy-1.14.1:
      Successfully uninstalled scipy-1.14.1
Note: you may need to restart the kernel to use updated packages.
